// Code generated by hive. DO NOT EDIT.

package rpc

import (
	"fmt"
	"github.com/benka-me/laruche/go-pkg/discover"
	"google.golang.org/grpc"
	"strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Sprintf("")
var _ = strconv.FormatInt(int64(0), 10)

type Clients struct {
}

func InitClients(engine discover.Engine, options ...grpc.DialOption) Clients {

	return Clients{}
}
